baseURL = "http://example.org/"
languageCode = "en-us"
theme = "exampleTheme"
title = "Netlify ny titel från kod"
[[menu.main]]
name = "Contact"
weight = 4
[[menu.main]]
name = "Tags"
pre = "tag"
url = "/tags/"
weight = 3
[[menu.main]]
name = "Posts"
pre = "pen-tool"
url = "/posts/"
weight = 2
[[menu.main]]
name = "Home"
pre = "home"
url = "/"
weight = 1
[params]
smalltext = "min lilla text"
[params.test]
testtext = "testTeXTTTT"
